FROM resin/raspberrypi3-python:3.6.2

WORKDIR /app

RUN apt-get update && \
    apt-get install libgtk2.0-dev && \
    apt-get install -y --no-install-recommends libboost-python1.55.0 python3-dev && \
    rm -rf /var/lib/apt/lists/* 

RUN pip install --upgrade setuptools 
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT [ "python", "-u", "./main.py" ]
