FROM resin/raspberrypi3-python:2.7

WORKDIR /app

RUN apt-get update && \
    apt-get install libgtk2.0-dev && \
    apt-get install -y --no-install-recommends libboost-python1.55.0 && \
    rm -rf /var/lib/apt/lists/* 

RUN pip install --upgrade setuptools 
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT [ "python", "-u", "./example_ble_azure_1.py" ]
